### ISSUE TITLE
Issuing a GET for a file that doesn't exist on server causes Node Red to crash

### ISSUE THREAD

**Issue by juggledad** [joeartsea/node-red-contrib-ftp#8]
If you try to GET a nonexistent file, Node Red will crash with the following:

20 Jul 05:13:29 - [info] Node-RED version: v0.17.4
20 Jul 05:13:29 - [info] Node.js  version: v6.11.0
20 Jul 05:13:29 - [info] Darwin 15.6.0 x64 LE
<...snip...>
20 Jul 05:14:02 - [red] Uncaught Exception:
20 Jul 05:14:02 - TypeError: Cannot read property 'once' of undefined
    at sendMsg (/Users/Paul/.node-red/node_modules/node-red-contrib-ftp/ftp.js:66:19)
    at Object.cb (/Users/Paul/.node-red/node_modules/ftp/lib/connection.js:606:15)
    at Parser.<anonymous> (/Users/Paul/.node-red/node_modules/ftp/lib/connection.js:113:22)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/Users/Paul/.node-red/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:331:12)
    at writeOrBuffer (_stream_writable.js:317:5)
    at Parser.Writable.write (_stream_writable.js:243:11)
    at Socket.ondata (/Users/Paul/.node-red/node_modules/ftp/lib/connection.js:273:20)
Pauls-mini:.node-red Paul$ 

note: NR running on a Mac

**Comment by juggledad** [comment]
The fix is as follows
edit ftp.js and moved line 54

    if (this.ftpConfig) {
      var conn = new ftp();                               <<==== this is line 54
      var node = this;
      node.on('input', function (msg) {
        var filename = node.filename || msg.filename || '';
        var localFilename = node.localFilename || msg.localFilename || '';
        this.sendMsg = function (err, result) {

to this location

    if (this.ftpConfig) {
      var node = this;
      node.on('input', function (msg) {
        var conn = new ftp();                              <<==== new location of old line 54
        var filename = node.filename || msg.filename || '';
        var localFilename = node.localFilename || msg.localFilename || '';
        this.sendMsg = function (err, result) {

**Comment by joeartsea** [comment]
#12
